services:
   db:
     image: mysql:5.7
     volumes:
       - ./volume/db_data:/var/lib/mysql
     restart: always
     environment:
       MYSQL_ROOT_PASSWORD: somewordpress
       MYSQL_DATABASE: wordpress
       MYSQL_USER: doan              
       MYSQL_PASSWORD: johnson        
     networks:
       ovpn-network:
         ipv4_address: 30.30.30.6
     cap_add:
       - NET_ADMIN  

   wordpress:
     depends_on:
       - db
     image: wordpress:latest
     restart: always
     environment:
       WORDPRESS_DB_HOST: db:3306
       WORDPRESS_DB_USER: doan          
       WORDPRESS_DB_PASSWORD: johnson   
       WORDPRESS_DB_NAME: wordpress
     networks:
       ovpn-network:
         ipv4_address: 30.30.30.7  
     command: >
       /bin/bash -c "apt-get update && apt-get install net-tools -y && route add -net 192.168.255.0 netmask 255.255.255.0 gw 30.30.30.2 && apache2-foreground"
     cap_add:
       - NET_ADMIN  
     volumes:
#       - ./volume/wordpress_data:/var/www
       - ./volume/wordpress_data/html:/var/www/html

   phpmyadmin:
     image: phpmyadmin/phpmyadmin:latest
     restart: always
     environment:
       PMA_HOST: db
       MYSQL_ROOT_PASSWORD: somewordpress
     networks:
       ovpn-network:
         ipv4_address: 30.30.30.8  

volumes:
    db_data: {}

networks:
  ovpn-network:
   name: ovpn-network
   external: true
