services:
  redis:
    image: vulhub/redis:5.0.7
    networks:
      ovpn-network:
        ipv4_address: 30.30.30.5
    cap_add:
      - NET_ADMIN
    command: >
       /bin/bash -c "apt-get update && apt-get install net-tools -y && route add -net 192.168.255.0 netmask 255.255.255.0 gw 30.30.30.2 && redis-server --bind 0.0.0.0"
    volumes:
      - ./volume/pirate-flag.png:/etc/pirate-flag.png

networks:
  ovpn-network:
    name: ovpn-network
    external: true
