services:
  cmd:
    image: vulhub/polkit:0.105
    networks:
      ovpn-network:
        ipv4_address: 30.30.30.10

  web:
    image: nginx:latest
    volumes:
      - ./volume/html:/usr/share/nginx/html
    networks:
      ovpn-network:
        ipv4_address: 30.30.30.30
    
networks:
  ovpn-network:
    external:
      name: ovpn-network
