services:
  web_ssh:
    image: nginx_ssh_vulnlab:latest
    container_name: web_ssh_server
    restart: unless-stopped
    networks:
      ovpn-network:
        ipv4_address: 30.30.30.21
    volumes:
       - ./volume/index.nginx-debian.html:/var/www/html/index.nginx-debian.html
       - ./volume/robots.txt:/var/www/html/robots.txt
       - ./volume/notes:/var/www/html/notes
       - ./volume/flag.txt:/root/flag.txt

networks:
  ovpn-network:
    name: ovpn-network
    external: true
